Fix clang 20 build issues
It is observed that with recent change of clang to 20 there are some CI
issues introduced, therefore fixed the same.

error: included header cstdint is not used directly
[misc-include-cleaner,-warnings-as-errors]
    3 | #include <cstdint>
      | ^~~~~~~~~~~~~~~~~~

Change-Id: I2c7752d960691572970fcbed331bc61149387bb2
Signed-off-by: Chandramohan Harkude <chandramohan.harkude@gmail.com>