Deprecate std::filesystem namespace include
Clang-tidy is complaining about our using fs = ... directives.  These
were originally added to handle boost::filesystem vs
std::experimental::filesystem vs std::filesystem between the various
compilers.  Now that we're all on std::filesystem, this redefintion can
be removed.

```
ChassisIntrusionSensor.hpp:11:11: error: namespace alias decl 'fs' is unused [misc-unused-alias-decls,-warnings-as-errors]
   11 | namespace fs = std::filesystem;
```

Tested: code compiles

Change-Id: If4b968ff9cceb4038f526321d3c7c11563ffbce9
Signed-off-by: Ed Tanous <etanous@nvidia.com>