subprojects: Bump boost to 1.83
Bump to avoid issues such as the following:

```
In file included from ../src/Utils.hpp:3,
                 from ../src/Thresholds.hpp:3,
                 from ../src/sensor.hpp:6,
                 from ../src/PwmSensor.hpp:3,
                 from ../src/PwmSensor.cpp:17:
../src/VariantVisitors.hpp:18:10: fatal error: boost/type_index.hpp: No such file or directory
   18 | #include <boost/type_index.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~
```

1.83 is used by openbmc/openbmc@43471c8c565d346c1727ba2360db373035234c26

With the bump I can now successfully build dbus-sensors on Debian
Bookworm with `meson setup --cross-file=gcc-13 build`[1], even if boost
libraries and headers of varying version are installed via `apt`.

[1]: https://amboar.github.io/notes/2023/09/12/unstable-gcc-on-debian-stable.html

Change-Id: I43cb95167ede3271cc6ce6ea6ea5421911b575c0
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>