NVMeSensor: Fix ordering of member initializer list
Resolves:

In file included from ../src/NVMeSensor.cpp:17:
../include/NVMeSensor.hpp: In constructor ‘NVMeSensor::NVMeSensor(sdbusplus::asio::object_server&, boost::asio::io_service&, std::shared_ptr<sdbusplus::asio::connection>&, const string&, std::vector<thresholds::Threshold>&&, const string&, int)’:
../include/NVMeSensor.hpp:22:37: error: ‘NVMeSensor::objServer’ will be initialized after [-Werror=reorder]
   22 |     sdbusplus::asio::object_server& objServer;
      |                                     ^~~~~~~~~
../include/NVMeSensor.hpp:19:9: error:   ‘int NVMeSensor::bus’ [-Werror=reorder]
   19 |     int bus;
      |         ^~~
../src/NVMeSensor.cpp:25:1: error:   when initialized here [-Werror=reorder]
   25 | NVMeSensor::NVMeSensor(sdbusplus::asio::object_server& objectServer,
      | ^~~~~~~~~~

Fixes: 1263c3dad3a7 ("Modify set-value function from external")
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: I7780400cc97349ac8a3553d8515ebf8d8668b5a0