mctp: Implement endpoint recovery state machine
The addition of the following action property to the openbmc_usb_mctp
spec:

```
[][~(\A dev \in Devices: reactor_eps[dev] = "recovered" /\ reactor_eps[dev]' = "removing")]_reactor_eps
```

yields the following 25-step violation:

```
Error: Action property ... of module openbmc_usb_mctp is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "unmanaged")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {}

State 2: <Plug line 86, col 5 to line 92, col 145 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "unmanaged")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 3: <UsbConfigQEvent line 248, col 5 to line 255, col 150 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "unmanaged")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "present"]>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 4: <InventoryQEvent line 238, col 5 to line 245, col 150 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "unmanaged")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "present"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "present"]>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {}

State 5: <MctpIfaceQEvent line 228, col 5 to line 235, col 156 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "unmanaged")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "present"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {}

State 6: <ReactorDeviceQEvent line 206, col 5 to line 225, col 141 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<[dev |-> d1, action |-> "assign"]>>
/\ assigned = {}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {}

State 7: <MctpdQEvent line 159, col 5 to line 177, col 112 of module openbmc_usb_mctp>
/\ mctpd_offers = {d1}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {}

State 8: <DeviceAcceptOffer line 146, col 5 to line 150, col 141 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {d1}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {d1}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {}

State 9: <MctpdControlEvent line 139, col 5 to line 143, col 135 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {d1}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {d1}

State 10: <Unplug line 95, col 5 to line 104, col 114 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {}
/\ dev_accepts = {}
/\ usb_config_q = <<[dev |-> d1, state |-> "unplugged"]>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "unplugged"]>>
/\ mctpd_assigned = {d1}

State 11: <UsbConfigQEvent line 248, col 5 to line 255, col 150 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "absent"]>>
/\ inventory_q = <<[dev |-> d1, state |-> "unplugged"]>>
/\ mctpd_assigned = {d1}

State 12: <InventoryQEvent line 238, col 5 to line 245, col 150 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "absent"]>>
/\ inventory_q = <<>>
/\ mctpd_assigned = {d1}

State 13: <Plug line 86, col 5 to line 92, col 145 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "absent"]>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {d1}

State 14: <MctpIfaceQEvent line 228, col 5 to line 235, col 156 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {d1}

State 15: <UsbConfigQEvent line 248, col 5 to line 255, col 150 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigning")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "present"]>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {d1}

State 16: <ReactorEndpointQEvent line 190, col 5 to line 203, col 151 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigned")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "present"]>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {d1}

State 17: <MctpdIfaceEvent line 153, col 5 to line 156, col 148 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigned")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "unmanaged"]>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<[dev |-> d1, state |-> "present"]>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 18: <MctpIfaceQEvent line 228, col 5 to line 235, col 156 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "assigned")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "unmanaged"]>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 19: <ReactorEndpointQEvent line 190, col 5 to line 203, col 151 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "lost")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 20: <ReactorDeferredSetup line 180, col 5 to line 187, col 156 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "recovering")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<[dev |-> d1, action |-> "assign"]>>
/\ assigned = {}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 21: <MctpdQEvent line 159, col 5 to line 177, col 112 of module openbmc_usb_mctp>
/\ mctpd_offers = {d1}
/\ reactor_eps = (d1 :> "recovering")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 22: <DeviceAcceptOffer line 146, col 5 to line 150, col 141 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "recovering")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {d1}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {d1}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {}

State 23: <MctpdControlEvent line 139, col 5 to line 143, col 135 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "recovering")
/\ reactor_ep_q = <<[dev |-> d1, state |-> "managed"]>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {d1}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {d1}

State 24: <ReactorEndpointQEvent line 190, col 5 to line 203, col 151 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "recovered")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<[dev |-> d1, state |-> "absent"]>>
/\ mctpd_q = <<>>
/\ assigned = {d1}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {d1}

State 25: <ReactorDeviceQEvent line 206, col 5 to line 225, col 141 of module openbmc_usb_mctp>
/\ mctpd_offers = {}
/\ reactor_eps = (d1 :> "removing")
/\ reactor_ep_q = <<>>
/\ reactor_dev_q = <<>>
/\ mctpd_q = <<[dev |-> d1, action |-> "remove"]>>
/\ assigned = {d1}
/\ ifaces = {d1}
/\ devs = {d1}
/\ dev_accepts = {}
/\ usb_config_q = <<>>
/\ mctp_iface_q = <<>>
/\ inventory_q = <<[dev |-> d1, state |-> "plugged"]>>
/\ mctpd_assigned = {d1}
```

Rework mctpreactor's endpoint state machine to mitigate a delayed
inventory event removing access to an already-recovered endpoint.
In practice, this may appear in the system logs like below, where
the violation is highlighted by pldmd's report of a failure to send
a message during 09:54:54, bounded by mctpreactor removing then
adding the device's endpoint in response to the inventory events from
entity-manager.

```
Feb 27 09:54:43 bmc kernel: usb 1-1: USB disconnect, device number 3
Feb 27 09:54:43 bmc systemd-networkd[556]: mctpusb0: Link DOWN
Feb 27 09:54:43 bmc systemd-networkd[556]: mctpusb0: Lost carrier
Feb 27 09:54:43 bmc systemd-timesyncd[265]: Network configuration changed, trying to establish connection.
Feb 27 09:54:43 bmc mctpreactor[600]: Endpoint removed @ [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:43 bmc mctpreactor[600]: Removed MCTP endpoint from device: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:43 bmc mctpreactor[600]: Deferring setup for MCTP device at [ interface: mctpusb0 ]
Feb 27 09:54:44 bmc usb-device[421]: USB device removed with dev node: /dev/bus/usb/001/003
Feb 27 09:54:46 bmc kernel: usb 1-1: new high-speed USB device number 4 using npcm7xx-ehci
Feb 27 09:54:47 bmc kernel: usb 1-1: New USB device found, idVendor=0000, idProduct=0000, bcdDevice= 0.00
Feb 27 09:54:47 bmc kernel: usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb 27 09:54:47 bmc kernel: usb 1-1: Product: MCTP over USB device
Feb 27 09:54:47 bmc kernel: usb 1-1: Manufacturer: mctp-dev
Feb 27 09:54:47 bmc kernel: usb 1-1: SerialNumber: sn0000
Feb 27 09:54:47 bmc mctpd[553]: mctpd: Warning, interface mctpusb0 is down
Feb 27 09:54:47 bmc mctpreactor[600]: Attempting to setup up MCTP endpoint for device at [ interface: mctpusb0 ]
Feb 27 09:54:47 bmc mctpreactor[600]: Setup failed for MCTP device at [ interface: mctpusb0 ]: Permission denied
Feb 27 09:54:47 bmc mctpreactor[600]: Deferring setup for MCTP device at [ interface: mctpusb0 ]
Feb 27 09:54:47 bmc mctpreactor[600]: Setup failed for MCTP device at [ interface: mctpusb0 ]: Permission denied
Feb 27 09:54:47 bmc systemd-networkd[556]: mctpusb0: Link UP
Feb 27 09:54:47 bmc kernel: IPv6: ADDRCONF(NETDEV_CHANGE): mctpusb0: link becomes ready
Feb 27 09:54:47 bmc systemd-networkd[556]: mctpusb0: Gained carrier
Feb 27 09:54:52 bmc mctpreactor[600]: Attempting to setup up MCTP endpoint for device at [ interface: mctpusb0 ]
Feb 27 09:54:52 bmc pldmd[360]: Multipart negotiated for tid:'8' type:'7' size:'512'
Feb 27 09:54:52 bmc pldmd[360]: Failed to build FRU table due to inventory lookup, error - bad optional access
Feb 27 09:54:52 bmc pldmd[360]: DfOpen received. tid:8 fi:0 fd:0
Feb 27 09:54:52 bmc mctpreactor[600]: Added MCTP endpoint to device: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:52 bmc pldmd[360]: Transferring DfRead first part. tid:8 fd:0
Feb 27 09:54:52 bmc mctpreactor[600]: Endpoint entered available state: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:54 bmc entity-manager[491]: Inventory Removed: mctp-dev
Feb 27 09:54:54 bmc entity-manager[491]: Inventory Added: mctp-dev
Feb 27 09:54:54 bmc mctpreactor[600]: MCTP device inventory removed at '/xyz/openbmc_project/inventory/system/board/mctp_dev/mctpusb'
Feb 27 09:54:54 bmc mctpreactor[600]: Stopping management of MCTP device at [ interface: mctpusb0 ]
Feb 27 09:54:54 bmc mctpreactor[600]: Removing endpoint @ [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:54 bmc mctpreactor[600]: Endpoint removed @ [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:54 bmc mctpreactor[600]: Removed MCTP endpoint from device: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:54 bmc pldmd[360]: Failed to send pldmTransport message for TID '8', response code '-7'
Feb 27 09:54:54 bmc mctpreactor[600]: Creating USBCMCTPDDevice
Feb 27 09:54:54 bmc mctpreactor[600]: MCTP device inventory added at '/xyz/openbmc_project/inventory/system/board/mctp_dev/mctpusb'
Feb 27 09:54:54 bmc mctpreactor[600]: Attempting to setup up MCTP endpoint for device at [ interface: mctpusb0 ]
Feb 27 09:54:54 bmc mctpreactor[600]: Added MCTP endpoint to device: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:54:54 bmc mctpreactor[600]: Endpoint entered available state: [ network: 1, EID: 8 | interface: mctpusb0 ]
```

After the rework, the following behavior is observed, with no disruption
to the concurrent file transfer across reinitialisation of the
inventory:

```
Feb 27 09:35:36 bmc kernel: usb 1-1: USB disconnect, device number 5
Feb 27 09:35:36 bmc systemd-networkd[563]: mctpusb0: Link DOWN
Feb 27 09:35:36 bmc systemd-networkd[563]: mctpusb0: Lost carrier
Feb 27 09:35:36 bmc systemd-timesyncd[256]: Network configuration changed, trying to establish connection.
Feb 27 09:35:36 bmc mctpreactor[566]: Endpoint removed @ [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:35:36 bmc mctpreactor[566]: Removed MCTP endpoint from device: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:35:36 bmc mctpreactor[566]: Device 0x1a4ba75c ([ interface: mctpusb0 ]) transitioning from Enum(3) to Enum(5)
Feb 27 09:35:36 bmc usb-device[398]: USB device removed with dev node: /dev/bus/usb/001/005
Feb 27 09:35:37 bmc kernel: usb 1-1: new high-speed USB device number 6 using npcm7xx-ehci
Feb 27 09:35:37 bmc kernel: usb 1-1: New USB device found, idVendor=0000, idProduct=0000, bcdDevice= 0.00
Feb 27 09:35:37 bmc kernel: usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb 27 09:35:37 bmc kernel: usb 1-1: Product: MCTP over USB device
Feb 27 09:35:37 bmc kernel: usb 1-1: Manufacturer: mctp-dev
Feb 27 09:35:37 bmc kernel: usb 1-1: SerialNumber: sn0000
Feb 27 09:35:37 bmc mctpd[452]: mctpd: Warning, interface mctpusb0 is down
Feb 27 09:35:37 bmc mctpreactor[566]: Device 0x1a4ba75c ([ interface: mctpusb0 ]) transitioning from Enum(5) to Enum(6)
Feb 27 09:35:37 bmc mctpreactor[566]: Attempting to setup up MCTP endpoint for device at [ interface: mctpusb0 ]
Feb 27 09:35:37 bmc mctpreactor[566]: Setup failed for MCTP device at [ interface: mctpusb0 ], deferring: Permission denied
Feb 27 09:35:37 bmc mctpreactor[566]: Device 0x1a4ba75c ([ interface: mctpusb0 ]) transitioning from Enum(6) to Enum(5)
Feb 27 09:35:37 bmc kernel: IPv6: ADDRCONF(NETDEV_CHANGE): mctpusb0: link becomes ready
Feb 27 09:35:37 bmc systemd-networkd[563]: mctpusb0: Link UP
Feb 27 09:35:37 bmc systemd-networkd[563]: mctpusb0: Gained carrier
Feb 27 09:35:42 bmc mctpreactor[566]: Device 0x1a4ba75c ([ interface: mctpusb0 ]) transitioning from Enum(5) to Enum(6)
Feb 27 09:35:42 bmc mctpreactor[566]: Attempting to setup up MCTP endpoint for device at [ interface: mctpusb0 ]
Feb 27 09:35:42 bmc pldmd[355]: Multipart negotiated for tid:'8' type:'7' size:'512'
Feb 27 09:35:42 bmc pldmd[355]: Failed to build FRU table due to inventory lookup, error - bad optional access
Feb 27 09:35:42 bmc pldmd[355]: DfOpen received. tid:8 fi:0 fd:0
Feb 27 09:35:42 bmc pldmd[355]: Transferring DfRead first part. tid:8 fd:0
Feb 27 09:35:42 bmc mctpreactor[566]: Added MCTP endpoint to device: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:35:42 bmc mctpreactor[566]: Device 0x1a4ba75c ([ interface: mctpusb0 ]) transitioning from Enum(6) to Enum(7)
Feb 27 09:35:42 bmc mctpreactor[566]: Endpoint entered available state: [ network: 1, EID: 8 | interface: mctpusb0 ]
Feb 27 09:35:43 bmc entity-manager[462]: Inventory Removed: mctp-dev
Feb 27 09:35:43 bmc entity-manager[462]: Inventory Added: mctp-dev
Feb 27 09:35:43 bmc mctpreactor[566]: MCTP device inventory removed at '/xyz/openbmc_project/inventory/system/board/mctp_dev/mctpusb'
Feb 27 09:35:43 bmc mctpreactor[566]: Creating USBCMCTPDDevice
Feb 27 09:35:43 bmc mctpreactor[566]: MCTP device inventory added at '/xyz/openbmc_project/inventory/system/board/mctp_dev/mctpusb'
Feb 27 09:35:43 bmc mctpreactor[566]: Device 0x1a4ba75c ([ interface: mctpusb0 ]) transitioning from Enum(7) to Enum(3)
Feb 27 09:35:45 bmc pldmd[355]: Transferring DfRead last part. tid:8 fd:0
Feb 27 09:35:45 bmc pldmd[355]: DfClose received. tid:8 fd:0 sentSize:246156
```

Change-Id: I66e523dcb988100bc7178ef9959d4a571708fba6
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>